### ISSUE TITLE
Python support

### ISSUE THREAD

**Issue by gilbertohasnofb** [twifty/atom-switch-quotes#1]
Is Python supported by this package? I absolutely love the idea and it would be a time saver, but unfortunately none of the commands seem to do anything on my py files.

**Comment by gilbertohasnofb** [comment]
I tested your package with a JavaScript code and it worked as expected. I see that you have definitions for only JavaScript and PHP. Perhaps it would be a good idea to include a simple default behaviour for any language, something to cover the most basic operations:

`'foo bar'` -> `"foo bar"`
`"foo bar"` -> `'foo bar'`
`"I'm foo"` -> `'I\'m foo'`
`'I\'m bar'` -> `"I'm bar"`
`'foo "bar"'` -> `"foo \"bar\""`
`"foo \"bar\""` -> `'foo "bar"'`

**Comment by gilbertohasnofb** [comment]
> In order for me to support new languages, I need first need to know how the strings in that language are structured. Giving me a sample file containing all possible string types, multiline types and interpolated types will speed up the process.

In case you want to add Python support, here is the list of all string formats it uses as requested.

```
# single and double quotes are always interchangeable
'foobar'
"foobar"

'\tFoo\nBar'    # \t for tab, \n for new line
'\\tFoo\\nBar'  # escaped backslashes, prints \\tFoo\\nBar without tabs or new lines
r'\tFoo\nBar'   # raw string, all backslashes are automatically escaped, prints \\tFoo\\nBar
u'Foobar'       # unicode string, redundant in Python 3 but still present in legacy code

pi = 3.1415
print(f'The value of pi is approximately {pi}.')   # format string (aka f-string) with automatic variable substitution
print(fr'The value of pi is approximately {pi}.')  # f-strings can also be raw

# multi-line strings: start with three quotes and end with three quotes
"""foo
bar
"""

'''foo
bar
'''

# they can also have just a single line, of course
"""foobar"""
'''foobar'''

# triple quoted strings are identified as docstrings when they come immediately after a function, class, or method definition, or at the top of a module. E.g.:
def foo():
    """The function foo does bar"""
    return None
```

**Comment by twifty** [comment]
Adding support for python is a little more involved than other languages. This plugin makes use of the atom language syntax and parsing to distinguish strings. With python, all strings are simply tagged as 'quoted string'. In order to add this I'll need to use regular expressions for each type of string. I like a challenge though.

In the above example:
```python
print(f'The value of pi is approximately {pi}.')   # format string (aka f-string) with automatic variable substitution
```
What expressions can be added between the curly braces? If it's only variable names, then what are legal variable names (think in terms of regex matching). If code snippets can be added then I might have to rethink things. I've never had the need to use python and always use bash for simple things or plain c for anything more involved.

**Comment by gilbertohasnofb** [comment]
> Adding support for python is a little more involved than other languages. [...] I like a challenge though.

That's really nice to hear. To be honest, just having a basic support for flipping between `'foobar'` and `"foobar"` would already be great for 99% of the cases, but full support would be absolutely wonderful.

> What expressions can be added between the curly braces? 

The most common use of curly brackets is for variable substitution, but they actually can accept any valid Python expression. E.g.:

```
>>> a = 1
>>> b = 2
>>> f'test {a + b}'
'test 3'
>>> f'test {a is b}'
'test False'
>>> f'test {a == 1}'
'test True'
>>> f'test {b ** (1/2)}'
'test 1.4142135623730951'
>>> f'test {[x for x in range(3)]}'
'test [0, 1, 2]'
```

So it's only expressions, not any code snippets that can get parsed by an f-string. For instance, you can't define a function, not even a lambda one, inside the brackets. But you can have fancy expressions such as list comprehensions (the last example above).

As for variable names, this is how they work in Python:

> A variable name must start with a letter or the underscore character. A variable name cannot start with a number. A variable name can only contain alpha-numeric characters and underscores (A-z, 0-9, and _ ) Variable names are case-sensitive (age, Age and AGE are three different variables)

**Comment by gilbertohasnofb** [comment]
Do let me know if I can help with anything, and thanks for taking a look at this, I really appreciate it!

**Comment by twifty** [comment]
>  To be honest, just having a basic support for flipping between 'foobar' and "foobar" would already be great for 99% of the cases

The plugin uses the same rules that the editor uses for coloring code. Basically, quoted strings are assigned a `css` class. The problem is the name of these classes are different across all the code languages and even then one language may use different classes for different types of strings. The plugin doesn't search the text for quote characters, which would be impossible to do without parsing the whole file. There is no way of knowing if a quote character is the beginning of a string, the end or even escaped. This is how all the other plugins work, and that is why so many of them have problems.

Saying that though, I do see the need for such a function.

**Comment by gilbertohasnofb** [comment]
Great. Let me know if you need anything, help testing, code snippets for test cases, etc. And many thanks for taking a look at this.

**Comment by twifty** [comment]
The latest commit 8521fabb8bdfa214bad6545e71795ef45e03d9c1 includes support for python. I have also fixed the single/double quote toggle for all other languages.

You should be able to download the package with:
```
apm install https://github.com/twifty/atom-switch-quotes.git
```

`Ctrl+quote` will toggle between single and double quotes. `Alt+quote` will cycle between the various python strings. Selecting a word/variable within a string and pressing `Alt-quote` will transform that selection into an embedded value and use an f-string type.

Give it a test and let me know of any problems. If all is OK I'll update the package on atom.io

**Comment by gilbertohasnofb** [comment]
First of all, thank you so much for implementing this. This is _really_ useful for Python programmers who are as neurotic about quote sign consistency as I am.

The basic functionality is works absolutely fine but I do have a couple of comments of things that could be improved:
* it is great that you define two shortcuts, one for quickly switching between `'` and `"` and another for cycling through all other options. But it would be great if the `Ctrl + '` shortcut also toggled multi-line strings. So for instance, if you have `'foobar'`, hiting the shortcut once would lead to `"foobar"` and once again would lead back to `'foobar'`. But if you had `"""foobar"""`, pressing it once it would change the string to `'''foobar'''` and once again would take you back to  `"""foobar"""`. Do you think this behaviour would be possible?
* I do like that `Alt + '` cycles through all options, but it would be great if the basic shortcut also worked with those raw and unicode strings without changing its type. E.g. if you have `r'foobar'`, it would be great to press `Ctrl + '` and get `r"foobar"` and pressing it again would take you back to `r'foobar'`.
* many Python programmers use a package called [MagicPython](https://atom.io/packages/magicpython) which adds advanced syntax highlighting. For some reason, the quote switching is not working when I set the highlight to `MagicPython`; could it be that they define a different scope for strings? Here is their [list of scopes](https://github.com/MagicStack/MagicPython/blob/master/misc/scopes).

**Comment by twifty** [comment]
The problem with adding shortcuts like that is that they are very specific to one language. For example I don't know of any other language that prefixes strings with 'r' 'f' etc.

One thing which may work is if I add some kind of configuration file to enable users to specify how exactly one string should be changed into another. You, as a user, should then be able to create a json/cson file like:

```json
{
  "python": [
     ["single.quote", "double.quote"],
     ["raw.single.quote", "raw.double.quote"]
  ]
}
```

I could add a new function to handle these tables, and users could add their own, or even remap the existing keymap shortcuts. Given how I've already recoded most of the package, it shouldn't be too difficult to implement.

`MagicPython` only extends on the existing scopes, so my package should work. I'll install it and take a look.

**Comment by gilbertohasnofb** [comment]
Fantastic, thank you so much. I'd be happy to test it once you push any modifications.

**Comment by twifty** [comment]
Latest commit now supports `MagicPython` (they use a different grammar name). You will also find that toggle `Ctrl + '` will only change the quote type, but it requires a config file.

In your .atom directory, create a file called "switch-quotes.cson" and add the following:
```cson
'python':
	[
		['single.quote', 'double.quote'],
		['raw/single.quote', 'raw/double.quote'],
		['formatted/single.quote', 'formatted/double.quote'],
		['formatted/raw/single.quote', 'formatted/raw/double.quote'],
		['unicode/single.quote', 'unicode/double.quote'],
		['multi.single','multi.double'],
		['multi.raw/multi.single','multi.raw/multi.double'],
		['multi.formatted/multi.single','multi.formatted/multi.double'],
		['multi.formatted/multi.raw/multi.single','multi.formatted/multi.raw/multi.double'],
	]
'MagicPython':
	[
		['single.quote', 'double.quote'],
		['raw/single.quote', 'raw/double.quote'],
		['formatted/single.quote', 'formatted/double.quote'],
		['formatted/raw/single.quote', 'formatted/raw/double.quote'],
		['unicode/single.quote', 'unicode/double.quote'],
		['multi.single','multi.double'],
		['multi.raw/multi.single','multi.raw/multi.double'],
		['multi.formatted/multi.single','multi.formatted/multi.double'],
		['multi.formatted/multi.raw/multi.single','multi.formatted/multi.raw/multi.double'],
	]
```
Again, I'll let you test it out (I don't use python) before I update atom.io

**Comment by twifty** [comment]
Fixed in bcdaca2ef68c200a4959c62720ea1fbbfbf1a9dd

Users can specify a toggle file in the .atom dir to override internal, but for python and javascript, the internal rules should be adequate.

**Comment by gilbertohasnofb** [comment]
@twifty This is really excellent, thank you so much. With the default Python syntax, it works flawlessly. With MagicPython, I still experienced a couple of minor issues:

* raw strings do not switch in MagicPython, both `r"foobar"` and `r"""foobar"""`
* multiline strings can be switched only when they have no letter preceeding it, such as `"""foobar"""`, or with a f-string `f"""foobar"""`. When using `r"""foobar"""` or `u"""foobar"""`, the quotes do not switch.
* `alt + '`: in MagicPython, it rotates the options until it reaches `fr''foobar"`, at which point it stops cycling. I believe this might be related to the very first point above.

**Comment by twifty** [comment]
Thanks for the feedback. I've managed to reproduce it by modifying the test file you posted above (strings were not assigned to variables).

It looks like MagicPython treats raw strings as regular-expressions. Their scope name includes the `regexp` class. Shouldn't be too difficult to fix.

**Comment by twifty** [comment]
Fixed in 7e07cb2f1747940e04e353f6c2d96b08ccb69090

**Comment by gilbertohasnofb** [comment]
@twifty Fantastic, MagicPython seems to work exactly as the default Python syntax. 

I did find one other only small bug: when changing quotes for f-strings that contain escaped quotation marks, things get messy: `f"foo'bar"` --> `f'foo\'bar'` --> `f"'foo"\'bar'` --> `f'\'foo'\'bar'`. All other types of lettered strings (`u"foobar"`, `r"foobar"`, `fr"foobar"` work fine).

Other than that, everything works wonderfully well. But if I may make a suggestion, it might be worth it to mention the file `~/.atom/switch-quotes.cson` in the README or elsewhere in the documentation.

**Comment by twifty** [comment]
I'll look into that. The cson file is not required anymore, I added it directly to the internal rules. So I'm not sure if I'll remove the feature at some point.

**Comment by twifty** [comment]
Try out ac7473f7a0e39dc5c8cfd5e95e6cf97cc862aa46

**Comment by gilbertohasnofb** [comment]
Phenomenal, looks really good. Thank you _so_ much for the new features.

**Comment by twifty** [comment]
No problem. Test it out for a bit and let me know of any further issues.

**Comment by gilbertohasnofb** [comment]
Great, I will do that, many thanks once again!

**Comment by twifty** [comment]
I can also confirm the update is working. I thought something was wrong when ksysguard showed constant fan speeds.

**Comment by gilbertohasnofb** [comment]
@twifty I tested a bit more and everything seems to be working fine. Perhaps you could consider to make a new release. This way you can also get more people to test the package. Thanks again for all the work!

**Comment by twifty** [comment]
Version 0.2.0 published with python/MagicPython/C/C++ support
